//! Cross-capability context compaction workflow.
//!
//! The execution capability owns context versions and compact summaries while
//! Sessions owns the visible timeline item. The application layer keeps their
//! state and public events in the same transaction and runs the command through
//! the durable operation worker.

use chrono::Duration;
use serde::Deserialize;
use serde_json::{Value, json};

use super::Application;
use super::operation_kinds::KIND_CONTEXT_COMPACT;
use janus_execution::interface::{
    DEFAULT_CONTEXT_LIMIT, ScheduleCompactInput, context_usage_near_limit,
};
use janus_models::interface::{
    AttemptType, ChatMessage, ChatRole, ContentPart, ModelRequest, ModelStreamEvent,
};
use janus_infrastructure::clock::{format_utc, now_utc, now_utc_str};
use janus_infrastructure::events::{EventType, NewEvent};
use janus_infrastructure::id::{CompactSummaryId, CorrelationId, SessionId};
use janus_infrastructure::operations::{
    CreateOperation, CreateWork, IdempotencyOutcome, IdempotencyRequest, OperationStatus,
    OperationView, StepState, WorkClaim,
};
use janus_sessions::interface::{ContextCompactedTimelineInput, SessionsError};

pub struct CompactContextRequest {
    pub owner_id: String,
    pub session_id: SessionId,
    pub actor: Value,
    pub correlation_id: CorrelationId,
    pub idempotency: IdempotencyRequest,
    pub context_limit: Option<i64>,
}

impl Application {
    pub(crate) async fn auto_compact_idle_sessions(&self) -> Result<(), SessionsError> {
        for session_id in self.sessions().ready_session_ids().await? {
            let Some(usage) = self
                .execution()
                .latest_context_usage(session_id)
                .await
                .map_err(|error| SessionsError::Internal(anyhow::anyhow!(error)))?
            else {
                continue;
            };
            if matches!(usage.compact_status.as_str(), "scheduled" | "running")
                || !context_usage_near_limit(usage.estimated_input_tokens, usage.context_limit)
            {
                continue;
            }

            let request = CompactContextRequest {
                owner_id: "system".to_owned(),
                session_id,
                actor: json!({"kind": "system", "reason": "context_threshold"}),
                correlation_id: CorrelationId::new(),
                idempotency: IdempotencyRequest {
                    key: format!("auto-context-compact:{session_id}:{}", usage.created_at),
                    owner_id: "system".to_owned(),
                    method: "AUTO".to_owned(),
                    normalized_route: format!("/internal/sessions/{session_id}/context/compact"),
                    digest: "auto-context-compact".to_owned(),
                    expires_at: format_utc(now_utc() + Duration::hours(24)),
                },
                context_limit: Some(usage.context_limit),
            };
            match self.request_context_compact(request).await {
                Ok(_) => {}
                Err(
                    SessionsError::ActiveTurnExists
                    | SessionsError::SessionDeleting
                    | SessionsError::Validation(_),
                ) => {}
                Err(error) => return Err(error),
            }
        }
        Ok(())
    }

    pub async fn request_context_compact(
        &self,
        input: CompactContextRequest,
    ) -> Result<OperationView, SessionsError> {
        let (source_first, source_last, item_count) =
            self.sessions().timeline_bounds(input.session_id).await?;
        let source_last = source_last.unwrap_or_else(|| "0".to_owned());
        // The durable placeholder records the covered range; the real summary
        // text is generated by the worker from the model (see
        // run_context_compact_operation) before completion is recorded.
        let summary = json!({
            "kind": "manual_compact",
            "title": "Context Compacted",
            "source_first_timeline_id": source_first,
            "source_last_timeline_id": source_last,
            "item_count": item_count,
            "message": "Prior timeline context is represented by this durable compact summary.",
        });
        let compact_summary_id = CompactSummaryId::new().to_string();
        let session_id = input.session_id.to_string();
        let payload = json!({
            "session_id": session_id,
            "compact_summary_id": compact_summary_id,
            "source_first_timeline_id": source_first.clone(),
            "source_last_timeline_id": source_last.clone(),
            "summary": summary.clone(),
            "actor": input.actor.clone(),
        });

        let mut work = self.unit_of_work().begin().await?;
        let created = self
            .operations()
            .create_in_tx(
                &mut work,
                CreateOperation {
                    kind: KIND_CONTEXT_COMPACT,
                    actor: payload
                        .get("actor")
                        .cloned()
                        .unwrap_or_else(|| json!({"kind": "owner", "id": input.owner_id})),
                    target_kind: "session",
                    target_id: Some(&session_id),
                    conditions: json!({
                        "session_id": session_id,
                        "compact_summary_id": compact_summary_id,
                    }),
                    correlation_id: input.correlation_id,
                    idempotency: Some(input.idempotency),
                },
                Some(CreateWork {
                    handler_kind: KIND_CONTEXT_COMPACT,
                    payload: payload.clone(),
                }),
            )
            .await
            .map_err(|error| SessionsError::Internal(anyhow::anyhow!(error)))?;

        if matches!(created.outcome, IdempotencyOutcome::New) {
            let current_session = self.sessions().get_session(input.session_id).await?;
            if current_session.state == "deleting" {
                return Err(SessionsError::SessionDeleting);
            }
            if current_session.active_turn_id.is_some() || current_session.state == "active" {
                return Err(SessionsError::ActiveTurnExists);
            }
            if self
                .execution()
                .context_compact_in_progress_in_tx(work.connection(), input.session_id)
                .await
                .map_err(|error| SessionsError::Internal(anyhow::anyhow!(error)))?
            {
                return Err(SessionsError::Validation(
                    "context compact is already in progress".into(),
                ));
            }
            let context_limit = if let Some(context_limit) = input
                .context_limit
                .filter(|context_limit| *context_limit > 0)
            {
                context_limit
            } else {
                self.execution()
                    .latest_context_usage(input.session_id)
                    .await
                    .map_err(|error| SessionsError::Internal(anyhow::anyhow!(error)))?
                    .map(|usage| usage.context_limit)
                    .filter(|context_limit| *context_limit > 0)
                    .unwrap_or(DEFAULT_CONTEXT_LIMIT)
            };
            self.execution()
                .schedule_context_compact_in_tx(
                    work.connection(),
                    ScheduleCompactInput {
                        session_id: input.session_id,
                        compact_summary_id: compact_summary_id.clone(),
                        source_first: payload
                            .get("source_first_timeline_id")
                            .and_then(Value::as_str)
                            .map(ToOwned::to_owned),
                        source_last: payload
                            .get("source_last_timeline_id")
                            .and_then(Value::as_str)
                            .unwrap_or("0")
                            .to_owned(),
                        summary: payload.get("summary").cloned().unwrap_or_default(),
                        estimated_input_tokens: 0,
                        context_limit,
                    },
                )
                .await
                .map_err(|error| SessionsError::Internal(anyhow::anyhow!(error)))?;
            work.append_event(NewEvent {
                event_type: EventType::ContextChanged,
                actor: payload
                    .get("actor")
                    .cloned()
                    .unwrap_or_else(|| json!({"kind": "owner", "id": input.owner_id})),
                resource: Some(json!({"kind": "session", "id": session_id})),
                correlation_id: input.correlation_id.to_string(),
                causation_id: Some(created.operation.id.clone()),
                payload: json!({
                    "session_id": session_id,
                    "compact_summary_id": compact_summary_id,
                    "compact_status": "scheduled",
                }),
            })
            .await
            .map_err(SessionsError::Internal)?;
        }
        work.commit().await?;
        Ok(created.operation)
    }
}

fn compact_timeline_digest(items: &[janus_sessions::interface::TimelineItemView]) -> String {
    const MAX_DIGEST_BYTES: usize = 120_000;
    let mut digest = String::new();
    for item in items {
        let projection = serde_json::to_string(&item.projection)
            .unwrap_or_else(|_| "{\"error\":\"projection unavailable\"}".to_owned());
        let mut line = String::new();
        line.push_str("[order=");
        line.push_str(&item.display_order.to_string());
        line.push_str("] ");
        line.push_str(&item.kind);
        if let Some(turn_id) = &item.turn_id {
            line.push_str(" turn=");
            line.push_str(turn_id);
        }
        line.push_str(": ");
        line.push_str(&projection);
        line.push('\n');
        let remaining = MAX_DIGEST_BYTES.saturating_sub(digest.len());
        if remaining == 0 {
            break;
        }
        if line.len() > remaining {
            let mut end = remaining;
            while end > 0 && !line.is_char_boundary(end) {
                end -= 1;
            }
            digest.push_str(&line[..end]);
            break;
        }
        digest.push_str(&line);
    }
    digest
}

#[derive(Debug, Deserialize)]
struct CompactContextWork {
    operation_id: String,
    session_id: String,
    compact_summary_id: String,
    source_first_timeline_id: Option<String>,
    source_last_timeline_id: String,
    summary: Value,
    actor: Value,
}

pub async fn run_context_compact_operation(
    state: &Application,
    payload: &Value,
    work_id: &str,
    work_nonce: &str,
) -> Result<(), anyhow::Error> {
    let input: CompactContextWork = serde_json::from_value(payload.clone())?;
    let session_id: SessionId = input.session_id.parse()?;
    let claim = WorkClaim {
        id: work_id,
        nonce: work_nonce,
    };
    let step = state
        .operations()
        .begin_step_claimed(
            claim,
            &input.operation_id,
            "compact_context",
            json!({
                "session_id": input.session_id,
                "compact_summary_id": input.compact_summary_id,
            }),
        )
        .await?;
    state.operations().assert_claimed(claim).await?;

    if matches!(step, StepState::Running | StepState::NeedsReconciliation) {
        let mut work = state.unit_of_work().begin().await?;
        let changed = state
            .execution()
            .begin_context_compact_in_tx(work.connection(), session_id, &input.compact_summary_id)
            .await?;
        if changed {
            work.append_event(NewEvent {
                event_type: EventType::ContextChanged,
                actor: input.actor.clone(),
                resource: Some(json!({"kind": "session", "id": input.session_id})),
                correlation_id: CorrelationId::new().to_string(),
                causation_id: Some(input.operation_id.clone()),
                payload: json!({
                    "session_id": input.session_id,
                    "compact_summary_id": input.compact_summary_id,
                    "compact_status": "running",
                }),
            })
            .await?;
        }
        work.commit().await?;
    }

    // Generate the real summary from the model. On any failure we degrade to
    // the mechanical digest so the compact still completes (the range it
    // covers is already hidden from later rounds), but the outcome is marked
    // so operators can see the model pass failed.
    let summary_outcome = state
        .generate_compact_summary(&input)
        .await
        .map_err(|error| anyhow::anyhow!("generate compact summary: {error:#}"))?;
    let summary = summary_outcome.summary;
    let estimated_input_tokens = summary_outcome.input_tokens;

    let now = now_utc_str();
    let mut work = state.unit_of_work().begin().await?;
    state
        .execution()
        .finalize_compact_summary_in_tx(
            work.connection(),
            &input.compact_summary_id,
            summary.clone(),
            summary_outcome.attempt_id.as_deref(),
            summary_outcome.input_tokens,
            summary_outcome.output_tokens,
        )
        .await?;
    let completed = state
        .execution()
        .complete_context_compact_in_tx(
            work.connection(),
            session_id,
            &input.compact_summary_id,
            estimated_input_tokens,
        )
        .await?;
    let (timeline_item_id, created) = state
        .sessions()
        .append_context_compacted_in_tx(
            work.connection(),
            ContextCompactedTimelineInput {
                session_id,
                compact_summary_id: &input.compact_summary_id,
                source_first_timeline_id: input.source_first_timeline_id.as_deref(),
                source_last_timeline_id: &input.source_last_timeline_id,
                summary: &summary,
                now: &now,
            },
        )
        .await?;
    let correlation_id = CorrelationId::new().to_string();
    if created {
        work.append_event(NewEvent {
            event_type: EventType::TimelineItemCreated,
            actor: input.actor.clone(),
            resource: Some(json!({"kind": "session", "id": input.session_id})),
            correlation_id: correlation_id.clone(),
            causation_id: Some(input.operation_id.clone()),
            payload: json!({
                "session_id": input.session_id,
                "timeline_item_id": timeline_item_id,
                "kind": "context_compacted",
                "compact_summary_id": input.compact_summary_id,
            }),
        })
        .await?;
    }
    if completed || created {
        work.append_event(NewEvent {
            event_type: EventType::ContextChanged,
            actor: input.actor,
            resource: Some(json!({"kind": "session", "id": input.session_id})),
            correlation_id,
            causation_id: Some(input.operation_id.clone()),
            payload: json!({
                "session_id": input.session_id,
                "compact_summary_id": input.compact_summary_id,
                "compact_status": "succeeded",
                "timeline_item_id": timeline_item_id,
            }),
        })
        .await?;
    }
    work.commit().await?;

    if matches!(step, StepState::Running | StepState::NeedsReconciliation) {
        state
            .operations()
            .complete_step_claimed(claim, &input.operation_id, "compact_context", None)
            .await?;
    }
    let finished = state
        .operations()
        .finish_claimed(
            &input.operation_id,
            work_id,
            work_nonce,
            janus_infrastructure::operations::OperationCompletion {
                status: OperationStatus::Succeeded,
                result: Some(json!({
                    "session_id": input.session_id,
                    "compact_summary_id": input.compact_summary_id,
                    "timeline_item_id": timeline_item_id,
                })),
                problem: None,
                correlation_id: CorrelationId::new(),
            },
        )
        .await?;
    if !finished {
        if state
            .operations()
            .get(&input.operation_id)
            .await?
            .is_some_and(|operation| operation.status == "succeeded")
        {
            return Ok(());
        }
        return Err(anyhow::anyhow!(
            "context compact operation lease became stale"
        ));
    }
    Ok(())
}

/// Result of the model-driven summary pass for one compact operation.
struct CompactSummaryOutcome {
    summary: Value,
    attempt_id: Option<String>,
    input_tokens: i64,
    output_tokens: i64,
}

const COMPACT_SUMMARY_SYSTEM_PROMPT: &str = r#"You are summarizing a coding-agent session transcript for context compaction. Produce a dense, self-contained summary a future assistant turn can use to continue the work without rereading the transcript.

Cover:
- The user's overall goal and any standing constraints or preferences.
- What was actually done: files changed, commands run, builds/tests executed and their outcomes.
- Tool and terminal results that still matter (failing tests, open PRs, repo state).
- Decisions made and their reasons, including approaches that were tried and rejected.
- Open threads: TODOs, unverified assumptions, known risks.

Rules:
- Write flowing prose or compact bullet lines; no preamble, no markdown headings.
- Be specific: real file paths, real error messages, real numbers.
- Never invent work that is not in the transcript.
- Keep it under 4000 words."#;

/// Max transcript characters fed to the summarizer. Long sessions are truncated
/// from the middle: the earliest context is the most stale, the tail carries
/// the live state, and both ends anchor continuity.
const MAX_COMPACT_TRANSCRIPT_CHARS: usize = 400_000;

impl Application {
    /// Run the model pass that turns the covered timeline range into a real
    /// compact summary. Degrades to the mechanical digest when no model is
    /// configured or the attempt fails, with the outcome recorded in the
    /// summary payload.
    async fn generate_compact_summary(
        &self,
        input: &CompactContextWork,
    ) -> Result<CompactSummaryOutcome, anyhow::Error> {
        let session_id: SessionId = input.session_id.parse()?;
        let session = self
            .sessions()
            .get_session(session_id)
            .await
            .map_err(|error| anyhow::anyhow!("load session for compact: {error}"))?;
        let project_id = session
            .project_id
            .parse::<janus_infrastructure::id::ProjectId>()
            .map_err(|error| anyhow::anyhow!("invalid project id: {error}"))?;
        let owner_id = self
            .projects()
            .owner_id(project_id)
            .await
            .map_err(|error| anyhow::anyhow!("resolve project owner: {error}"))?;

        let timeline = self
            .sessions()
            .timeline(session_id, None, None, 10_000)
            .await
            .map_err(|error| anyhow::anyhow!("load timeline for compact: {error}"))?;
        let transcript = compact_transcript(&timeline.items);
        let digest = compact_timeline_digest(&timeline.items);
        let summary_base = input.summary.clone();

        let mut request = {
            let mut work = self.unit_of_work().begin().await?;
            let snapshot = self
                .execution_coordinator()
                .resolve_model_snapshot_in_tx(
                    work.connection(),
                    project_id,
                    Some(owner_id.as_str()),
                    None,
                )
                .await
                .map_err(|error| anyhow::anyhow!("resolve compact model: {error}"))?;
            work.rollback().await?;
            snapshot
        };
        let Some(model_snapshot) = request.take() else {
            return Ok(CompactSummaryOutcome {
                summary: fallback_compact_summary(
                    &summary_base,
                    &transcript,
                    &digest,
                    "no_model_configured",
                    "no default model is configured for the project",
                ),
                attempt_id: None,
                input_tokens: 0,
                output_tokens: 0,
            });
        };

        let transcript = truncate_transcript_middle(transcript, MAX_COMPACT_TRANSCRIPT_CHARS);
        let messages = vec![
            ChatMessage {
                role: ChatRole::System,
                parts: vec![ContentPart::Text {
                    text: COMPACT_SUMMARY_SYSTEM_PROMPT.to_owned(),
                }],
                tool_call_id: None,
                tool_calls: Vec::new(),
                reasoning_content: None,
            },
            ChatMessage {
                role: ChatRole::User,
                parts: vec![ContentPart::Text {
                    text: format!(
                        "Summarize this session transcript for context compaction:\n\n{transcript}"
                    ),
                }],
                tool_call_id: None,
                tool_calls: Vec::new(),
                reasoning_content: None,
            },
        ];

        let req = ModelRequest {
            owner_id,
            provider_id: model_snapshot.provider_id,
            upstream_model_id: model_snapshot.upstream_model_id,
            parameters: model_snapshot.parameters,
            messages,
            tools: Vec::new(),
            // The attempt ledger row keys on this id; usage rows are only
            // written when the full turn/round correlation is present, which
            // is deliberately absent for compact attempts.
            round_id: Some(input.compact_summary_id.clone()),
            project_id: Some(project_id.to_string()),
            session_id: Some(input.session_id.clone()),
            turn_id: None,
        };
        let mut ignore_event = |_| std::future::ready(());
        let events = self
            .models()
            .stream_completion_with_attempt(
                req,
                AttemptType::Compact,
                &mut ignore_event,
            )
            .await
            .map_err(|error| anyhow::anyhow!("compact model stream: {error}"))?;

        match events.iter().rev().find_map(|event| match event {
            ModelStreamEvent::Completed {
                attempt_id,
                usage,
                text,
                ..
            } => Some((attempt_id.clone(), usage.clone(), text.clone())),
            _ => None,
        }) {
            Some((attempt_id, usage, text)) if !text.trim().is_empty() => {
                Ok(CompactSummaryOutcome {
                    summary: model_compact_summary(
                        &summary_base,
                        &text,
                        &usage,
                        attempt_id.as_str(),
                    ),
                    attempt_id: Some(attempt_id),
                    input_tokens: i64::try_from(usage.input_tokens).unwrap_or(i64::MAX),
                    output_tokens: i64::try_from(usage.output_tokens).unwrap_or(i64::MAX),
                })
            }
            _ => {
                let detail = events
                    .iter()
                    .rev()
                    .find_map(|event| match event {
                        ModelStreamEvent::Failed { detail, .. } => Some(detail.clone()),
                        _ => None,
                    })
                    .unwrap_or_else(|| "model produced no summary text".to_owned());
                Ok(CompactSummaryOutcome {
                    summary: fallback_compact_summary(
                        &summary_base,
                        &transcript,
                        &digest,
                        "model_failed",
                        &detail,
                    ),
                    attempt_id: None,
                    input_tokens: 0,
                    output_tokens: 0,
                })
            }
        }
    }
}

/// Render the timeline range covered by the compact as flat, model-readable
/// transcript text. Only conversation-relevant kinds are included; ephemeral
/// UI noise (stream markers, plan versions) is skipped.
fn compact_transcript(items: &[janus_sessions::interface::TimelineItemView]) -> String {
    let mut out = String::new();
    for item in items {
        let projection = &item.projection;
        let mut line = String::new();
        match item.kind.as_str() {
            "user_message" | "steer" => {
                let text = projection
                    .get("text")
                    .and_then(Value::as_str)
                    .unwrap_or_default();
                if text.trim().is_empty() {
                    continue;
                }
                line.push_str("[user]");
                if item.kind == "steer" {
                    line.push_str("[steer]");
                }
                line.push(' ');
                line.push_str(text.trim());
            }
            "assistant_message" => {
                let text = projection
                    .get("text")
                    .and_then(Value::as_str)
                    .unwrap_or_default();
                let reasoning = projection
                    .get("reasoning")
                    .and_then(Value::as_str)
                    .unwrap_or_default();
                if text.trim().is_empty() && reasoning.trim().is_empty() {
                    continue;
                }
                line.push_str("[assistant]");
                if !reasoning.trim().is_empty() {
                    line.push_str(" (reasoning: ");
                    line.push_str(reasoning.trim());
                    line.push(')');
                }
                if !text.trim().is_empty() {
                    line.push(' ');
                    line.push_str(text.trim());
                }
            }
            "tool_call" => {
                let tool_name = projection
                    .get("tool_name")
                    .and_then(Value::as_str)
                    .unwrap_or("tool");
                let status = projection
                    .get("status")
                    .and_then(Value::as_str)
                    .unwrap_or("unknown");
                let summary = projection.get("summary").cloned().unwrap_or(Value::Null);
                line.push_str("[tool ");
                line.push_str(tool_name);
                line.push_str(" -> ");
                line.push_str(status);
                line.push_str("] ");
                line.push_str(&summary.to_string());
            }
            "async_task_result" => {
                line.push_str("[task ");
                line.push_str(
                    projection
                        .get("command")
                        .and_then(Value::as_str)
                        .unwrap_or("bash"),
                );
                line.push_str("] ");
                line.push_str(
                    projection
                        .get("output")
                        .or_else(|| projection.get("text"))
                        .and_then(Value::as_str)
                        .unwrap_or_default(),
                );
            }
            "context_compacted" => {
                let prior = projection
                    .get("summary")
                    .and_then(|summary| summary.get("text"))
                    .and_then(Value::as_str)
                    .unwrap_or_default();
                if prior.is_empty() {
                    continue;
                }
                line.push_str("[prior compact summary]\n");
                line.push_str(prior);
            }
            _ => continue,
        }
        line.push_str("\n\n");
        out.push_str(&line);
    }
    out
}

/// Keep both ends of an over-long transcript and drop the middle.
fn truncate_transcript_middle(mut transcript: String, max_chars: usize) -> String {
    let total = transcript.chars().count();
    if total <= max_chars {
        return transcript;
    }
    let head = max_chars / 2;
    let tail = max_chars - head;
    let head_str: String = transcript.chars().take(head).collect();
    let tail_str: String = transcript.chars().skip(total - tail).collect();
    transcript.clear();
    transcript.push_str(&head_str);
    transcript.push_str("\n... [earlier transcript truncated] ...\n\n");
    transcript.push_str(&tail_str);
    transcript
}

fn model_compact_summary(
    base: &Value,
    text: &str,
    usage: &janus_models::interface::TokenUsage,
    attempt_id: &str,
) -> Value {
    let mut summary = base.clone();
    let object = summary
        .as_object_mut()
        .expect("compact summary base is an object");
    object.insert("text".into(), json!(text));
    object.insert(
        "model".into(),
        json!({
            "attempt_id": attempt_id,
            "input_tokens": usage.input_tokens,
            "output_tokens": usage.output_tokens,
        }),
    );
    summary
}

fn fallback_compact_summary(
    base: &Value,
    transcript: &str,
    digest: &str,
    status: &str,
    detail: &str,
) -> Value {
    let mut summary = base.clone();
    let object = summary
        .as_object_mut()
        .expect("compact summary base is an object");
    object.insert("summary_model_status".into(), json!(status));
    object.insert("summary_model_detail".into(), json!(detail));
    if !transcript.is_empty() {
        object.insert("timeline_digest".into(), json!(digest));
    }
    summary
}
